/*****************************************************************************
* Model: emitter_receiver_gateway.qm
* File:  ./include/erg.h
*
* This code has been generated by QM tool (see state-machine.com/qm).
* DO NOT EDIT THIS FILE MANUALLY. All your changes will be lost.
*
* This program is open source software: you can redistribute it and/or
* modify it under the terms of the GNU General Public License as published
* by the Free Software Foundation.
*
* This program is distributed in the hope that it will be useful, but
* WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
* or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License
* for more details.
*****************************************************************************/
/*${.::include::erg.h} .....................................................*/
#ifndef ERG_H
#define ERG_H

#include "qpn.h"
#include "Arduino.h"
#include "manchester.h"

#define BSP_TICKS_PER_SEC  100 // number of system clock ticks in one second
#define LED13_PIN          13  // the pin number of the on-board LED

#define RADIO433_TX_PIN    4   // 433mhz Emitter pin
#define RADIO433_RX_PIN    9   // 433mhz receiver pin
#define RADIO433_FACTOR    MAN_9600 // 433mhz default baudrate

// by default, HC5 BT module uses 9600bps,
// which means 4800 here since mini pro uses a x2 on transmit speed
#define UART_SPEED        4800
#define UART_POWER_CTRL_PIN 10

// How many ms for a BSP tick
const uint8_t BSP_TICK_DURATION_MS = 1000 / BSP_TICKS_PER_SEC -1;

#endif
