/*****************************************************************************
* Model: emitter_receiver_gateway.qm
* File:  ./include/led.h
*
* This code has been generated by QM tool (see state-machine.com/qm).
* DO NOT EDIT THIS FILE MANUALLY. All your changes will be lost.
*
* This program is open source software: you can redistribute it and/or
* modify it under the terms of the GNU General Public License as published
* by the Free Software Foundation.
*
* This program is distributed in the hope that it will be useful, but
* WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
* or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License
* for more details.
*****************************************************************************/
/*${.::include::led.h} .....................................................*/
#ifndef LED_H
#define LED_H

#include "erg.h"

enum LedSignals {
    LED_ON_SIG = Q_USER_SIG,
    LED_BLINK_SIG,
    LED_OFF_SIG,
    LED_RESET_SIG,
    LED_SETUP_SIG
};


#if ((QP_VERSION < 591) || (QP_VERSION != ((QP_RELEASE^4294967295U) % 0x3E8)))
#error qpn version 5.9.1 or higher required
#endif

/*${AOs::Led} ..............................................................*/
typedef struct Led {
/* protected: */
    QActive super;

/* public: */
    uint8_t m_BlinkCounter;
    uint8_t m_LedPin;
} Led;

/* protected: */
QState Led_initial(Led * const me);
QState Led_READY(Led * const me);
QState Led_OFF(Led * const me);
QState Led_ON(Led * const me);


#endif
